/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandRouteImport } from './routes/$brand'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SectoresRouteImport } from './routes/sectores'
import { Route as BrandIndexRouteImport } from './routes/$brand.index'
import { Route as BrandProductosRouteImport } from './routes/$brand.productos'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminMarcasRouteImport } from './routes/admin.marcas'
import { Route as AdminPanelRouteImport } from './routes/admin.panel'
import { Route as AdminPapeleraRouteImport } from './routes/admin.papelera'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminProductosRouteImport } from './routes/admin.productos'
import { Route as AdminProveedoresRouteImport } from './routes/admin.proveedores'
import { Route as CuentaComprasRouteImport } from './routes/cuenta.compras'
import { Route as CuentaDireccionesRouteImport } from './routes/cuenta.direcciones'
import { Route as CuentaFavoritosRouteImport } from './routes/cuenta.favoritos'
import { Route as CuentaPanelRouteImport } from './routes/cuenta.panel'
import { Route as CuentaPedidosRouteImport } from './routes/cuenta.pedidos'
import { Route as CuentaPerfilRouteImport } from './routes/cuenta.perfil'
import { Route as BrandProductoSlugRouteImport } from './routes/$brand.producto.$slug'
import { Route as ApiMercadopagoWebhookRouteImport } from './routes/api.mercadopago.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/$brand',
  path: '/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SectoresRoute = SectoresRouteImport.update({
  id: '/sectores',
  path: '/sectores',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandIndexRoute = BrandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandRoute,
} as any)
const BrandProductosRoute = BrandProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => BrandRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarcasRoute = AdminMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPanelRoute = AdminPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPapeleraRoute = AdminPapeleraRouteImport.update({
  id: '/papelera',
  path: '/papelera',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProveedoresRoute = AdminProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => AdminRoute,
} as any)
const CuentaComprasRoute = CuentaComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaDireccionesRoute = CuentaDireccionesRouteImport.update({
  id: '/direcciones',
  path: '/direcciones',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaFavoritosRoute = CuentaFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaPanelRoute = CuentaPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaPedidosRoute = CuentaPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => CuentaRoute,
} as any)
const CuentaPerfilRoute = CuentaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => CuentaRoute,
} as any)
const BrandProductoSlugRoute = BrandProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => BrandRoute,
} as any)
const ApiMercadopagoWebhookRoute = ApiMercadopagoWebhookRouteImport.update({
  id: '/api/mercadopago/webhook',
  path: '/api/mercadopago/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$brand': typeof BrandRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/cuenta': typeof CuentaRouteWithChildren
  '/login': typeof LoginRoute
  '/productos': typeof ProductosRoute
  '/register': typeof RegisterRoute
  '/sectores': typeof SectoresRoute
  '/$brand/productos': typeof BrandProductosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/panel': typeof AdminPanelRoute
  '/admin/papelera': typeof AdminPapeleraRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/proveedores': typeof AdminProveedoresRoute
  '/cuenta/compras': typeof CuentaComprasRoute
  '/cuenta/direcciones': typeof CuentaDireccionesRoute
  '/cuenta/favoritos': typeof CuentaFavoritosRoute
  '/cuenta/panel': typeof CuentaPanelRoute
  '/cuenta/pedidos': typeof CuentaPedidosRoute
  '/cuenta/perfil': typeof CuentaPerfilRoute
  '/$brand/': typeof BrandIndexRoute
  '/$brand/producto/$slug': typeof BrandProductoSlugRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/cuenta': typeof CuentaRouteWithChildren
  '/login': typeof LoginRoute
  '/productos': typeof ProductosRoute
  '/register': typeof RegisterRoute
  '/sectores': typeof SectoresRoute
  '/$brand/productos': typeof BrandProductosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/panel': typeof AdminPanelRoute
  '/admin/papelera': typeof AdminPapeleraRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/proveedores': typeof AdminProveedoresRoute
  '/cuenta/compras': typeof CuentaComprasRoute
  '/cuenta/direcciones': typeof CuentaDireccionesRoute
  '/cuenta/favoritos': typeof CuentaFavoritosRoute
  '/cuenta/panel': typeof CuentaPanelRoute
  '/cuenta/pedidos': typeof CuentaPedidosRoute
  '/cuenta/perfil': typeof CuentaPerfilRoute
  '/$brand': typeof BrandIndexRoute
  '/$brand/producto/$slug': typeof BrandProductoSlugRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$brand': typeof BrandRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/checkout': typeof CheckoutRoute
  '/cuenta': typeof CuentaRouteWithChildren
  '/login': typeof LoginRoute
  '/productos': typeof ProductosRoute
  '/register': typeof RegisterRoute
  '/sectores': typeof SectoresRoute
  '/$brand/productos': typeof BrandProductosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/panel': typeof AdminPanelRoute
  '/admin/papelera': typeof AdminPapeleraRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/proveedores': typeof AdminProveedoresRoute
  '/cuenta/compras': typeof CuentaComprasRoute
  '/cuenta/direcciones': typeof CuentaDireccionesRoute
  '/cuenta/favoritos': typeof CuentaFavoritosRoute
  '/cuenta/panel': typeof CuentaPanelRoute
  '/cuenta/pedidos': typeof CuentaPedidosRoute
  '/cuenta/perfil': typeof CuentaPerfilRoute
  '/$brand/': typeof BrandIndexRoute
  '/$brand/producto/$slug': typeof BrandProductoSlugRoute
  '/api/mercadopago/webhook': typeof ApiMercadopagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$brand'
    | '/admin'
    | '/carrito'
    | '/checkout'
    | '/cuenta'
    | '/login'
    | '/productos'
    | '/register'
    | '/sectores'
    | '/$brand/productos'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/marcas'
    | '/admin/panel'
    | '/admin/papelera'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/proveedores'
    | '/cuenta/compras'
    | '/cuenta/direcciones'
    | '/cuenta/favoritos'
    | '/cuenta/panel'
    | '/cuenta/pedidos'
    | '/cuenta/perfil'
    | '/$brand/'
    | '/$brand/producto/$slug'
    | '/api/mercadopago/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/carrito'
    | '/checkout'
    | '/cuenta'
    | '/login'
    | '/productos'
    | '/register'
    | '/sectores'
    | '/$brand/productos'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/marcas'
    | '/admin/panel'
    | '/admin/papelera'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/proveedores'
    | '/cuenta/compras'
    | '/cuenta/direcciones'
    | '/cuenta/favoritos'
    | '/cuenta/panel'
    | '/cuenta/pedidos'
    | '/cuenta/perfil'
    | '/$brand'
    | '/$brand/producto/$slug'
    | '/api/mercadopago/webhook'
  id:
    | '__root__'
    | '/'
    | '/$brand'
    | '/admin'
    | '/carrito'
    | '/checkout'
    | '/cuenta'
    | '/login'
    | '/productos'
    | '/register'
    | '/sectores'
    | '/$brand/productos'
    | '/admin/clientes'
    | '/admin/configuracion'
    | '/admin/marcas'
    | '/admin/panel'
    | '/admin/papelera'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/proveedores'
    | '/cuenta/compras'
    | '/cuenta/direcciones'
    | '/cuenta/favoritos'
    | '/cuenta/panel'
    | '/cuenta/pedidos'
    | '/cuenta/perfil'
    | '/$brand/'
    | '/$brand/producto/$slug'
    | '/api/mercadopago/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CarritoRoute: typeof CarritoRoute
  CheckoutRoute: typeof CheckoutRoute
  CuentaRoute: typeof CuentaRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProductosRoute: typeof ProductosRoute
  RegisterRoute: typeof RegisterRoute
  SectoresRoute: typeof SectoresRoute
  ApiMercadopagoWebhookRoute: typeof ApiMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$brand': {
      id: '/$brand'
      path: '/$brand'
      fullPath: '/$brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectores': {
      id: '/sectores'
      path: '/sectores'
      fullPath: '/sectores'
      preLoaderRoute: typeof SectoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$brand/': {
      id: '/$brand/'
      path: '/'
      fullPath: '/$brand/'
      preLoaderRoute: typeof BrandIndexRouteImport
      parentRoute: typeof BrandRoute
    }
    '/$brand/productos': {
      id: '/$brand/productos'
      path: '/productos'
      fullPath: '/$brand/productos'
      preLoaderRoute: typeof BrandProductosRouteImport
      parentRoute: typeof BrandRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marcas': {
      id: '/admin/marcas'
      path: '/marcas'
      fullPath: '/admin/marcas'
      preLoaderRoute: typeof AdminMarcasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/panel': {
      id: '/admin/panel'
      path: '/panel'
      fullPath: '/admin/panel'
      preLoaderRoute: typeof AdminPanelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/papelera': {
      id: '/admin/papelera'
      path: '/papelera'
      fullPath: '/admin/papelera'
      preLoaderRoute: typeof AdminPapeleraRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proveedores': {
      id: '/admin/proveedores'
      path: '/proveedores'
      fullPath: '/admin/proveedores'
      preLoaderRoute: typeof AdminProveedoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/cuenta/compras': {
      id: '/cuenta/compras'
      path: '/compras'
      fullPath: '/cuenta/compras'
      preLoaderRoute: typeof CuentaComprasRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/direcciones': {
      id: '/cuenta/direcciones'
      path: '/direcciones'
      fullPath: '/cuenta/direcciones'
      preLoaderRoute: typeof CuentaDireccionesRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/favoritos': {
      id: '/cuenta/favoritos'
      path: '/favoritos'
      fullPath: '/cuenta/favoritos'
      preLoaderRoute: typeof CuentaFavoritosRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/panel': {
      id: '/cuenta/panel'
      path: '/panel'
      fullPath: '/cuenta/panel'
      preLoaderRoute: typeof CuentaPanelRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/pedidos': {
      id: '/cuenta/pedidos'
      path: '/pedidos'
      fullPath: '/cuenta/pedidos'
      preLoaderRoute: typeof CuentaPedidosRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/cuenta/perfil': {
      id: '/cuenta/perfil'
      path: '/perfil'
      fullPath: '/cuenta/perfil'
      preLoaderRoute: typeof CuentaPerfilRouteImport
      parentRoute: typeof CuentaRoute
    }
    '/$brand/producto/$slug': {
      id: '/$brand/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/$brand/producto/$slug'
      preLoaderRoute: typeof BrandProductoSlugRouteImport
      parentRoute: typeof BrandRoute
    }
    '/api/mercadopago/webhook': {
      id: '/api/mercadopago/webhook'
      path: '/api/mercadopago/webhook'
      fullPath: '/api/mercadopago/webhook'
      preLoaderRoute: typeof ApiMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BrandRouteChildren {
  BrandProductosRoute: typeof BrandProductosRoute
  BrandIndexRoute: typeof BrandIndexRoute
  BrandProductoSlugRoute: typeof BrandProductoSlugRoute
}

const BrandRouteChildren: BrandRouteChildren = {
  BrandProductosRoute: BrandProductosRoute,
  BrandIndexRoute: BrandIndexRoute,
  BrandProductoSlugRoute: BrandProductoSlugRoute,
}

const BrandRouteWithChildren = BrandRoute._addFileChildren(BrandRouteChildren)

interface AdminRouteChildren {
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminMarcasRoute: typeof AdminMarcasRoute
  AdminPanelRoute: typeof AdminPanelRoute
  AdminPapeleraRoute: typeof AdminPapeleraRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminProveedoresRoute: typeof AdminProveedoresRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminMarcasRoute: AdminMarcasRoute,
  AdminPanelRoute: AdminPanelRoute,
  AdminPapeleraRoute: AdminPapeleraRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminProveedoresRoute: AdminProveedoresRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CuentaRouteChildren {
  CuentaComprasRoute: typeof CuentaComprasRoute
  CuentaDireccionesRoute: typeof CuentaDireccionesRoute
  CuentaFavoritosRoute: typeof CuentaFavoritosRoute
  CuentaPanelRoute: typeof CuentaPanelRoute
  CuentaPedidosRoute: typeof CuentaPedidosRoute
  CuentaPerfilRoute: typeof CuentaPerfilRoute
}

const CuentaRouteChildren: CuentaRouteChildren = {
  CuentaComprasRoute: CuentaComprasRoute,
  CuentaDireccionesRoute: CuentaDireccionesRoute,
  CuentaFavoritosRoute: CuentaFavoritosRoute,
  CuentaPanelRoute: CuentaPanelRoute,
  CuentaPedidosRoute: CuentaPedidosRoute,
  CuentaPerfilRoute: CuentaPerfilRoute,
}

const CuentaRouteWithChildren =
  CuentaRoute._addFileChildren(CuentaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CarritoRoute: CarritoRoute,
  CheckoutRoute: CheckoutRoute,
  CuentaRoute: CuentaRouteWithChildren,
  LoginRoute: LoginRoute,
  ProductosRoute: ProductosRoute,
  RegisterRoute: RegisterRoute,
  SectoresRoute: SectoresRoute,
  ApiMercadopagoWebhookRoute: ApiMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
