/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrandRouteImport } from './routes/$brand'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SectoresRouteImport } from './routes/sectores'
import { Route as BrandIndexRouteImport } from './routes/$brand.index'
import { Route as BrandCarritoRouteImport } from './routes/$brand.carrito'
import { Route as BrandCheckoutRouteImport } from './routes/$brand.checkout'
import { Route as BrandProductosRouteImport } from './routes/$brand.productos'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminMarcasRouteImport } from './routes/admin.marcas'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminProductosRouteImport } from './routes/admin.productos'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as BrandProductoSlugRouteImport } from './routes/$brand.producto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/$brand',
  path: '/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SectoresRoute = SectoresRouteImport.update({
  id: '/sectores',
  path: '/sectores',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandIndexRoute = BrandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandRoute,
} as any)
const BrandCarritoRoute = BrandCarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => BrandRoute,
} as any)
const BrandCheckoutRoute = BrandCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => BrandRoute,
} as any)
const BrandProductosRoute = BrandProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => BrandRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarcasRoute = AdminMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const BrandProductoSlugRoute = BrandProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => BrandRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$brand': typeof BrandRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cuenta': typeof CuentaRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sectores': typeof SectoresRoute
  '/$brand/carrito': typeof BrandCarritoRoute
  '/$brand/checkout': typeof BrandCheckoutRoute
  '/$brand/productos': typeof BrandProductosRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/$brand/': typeof BrandIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$brand/producto/$slug': typeof BrandProductoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuenta': typeof CuentaRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sectores': typeof SectoresRoute
  '/$brand/carrito': typeof BrandCarritoRoute
  '/$brand/checkout': typeof BrandCheckoutRoute
  '/$brand/productos': typeof BrandProductosRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/$brand': typeof BrandIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$brand/producto/$slug': typeof BrandProductoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$brand': typeof BrandRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/cuenta': typeof CuentaRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sectores': typeof SectoresRoute
  '/$brand/carrito': typeof BrandCarritoRoute
  '/$brand/checkout': typeof BrandCheckoutRoute
  '/$brand/productos': typeof BrandProductosRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/$brand/': typeof BrandIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$brand/producto/$slug': typeof BrandProductoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$brand'
    | '/admin'
    | '/cuenta'
    | '/login'
    | '/register'
    | '/sectores'
    | '/$brand/carrito'
    | '/$brand/checkout'
    | '/$brand/productos'
    | '/admin/marcas'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/configuracion'
    | '/$brand/'
    | '/admin/'
    | '/$brand/producto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cuenta'
    | '/login'
    | '/register'
    | '/sectores'
    | '/$brand/carrito'
    | '/$brand/checkout'
    | '/$brand/productos'
    | '/admin/marcas'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/configuracion'
    | '/$brand'
    | '/admin'
    | '/$brand/producto/$slug'
  id:
    | '__root__'
    | '/'
    | '/$brand'
    | '/admin'
    | '/cuenta'
    | '/login'
    | '/register'
    | '/sectores'
    | '/$brand/carrito'
    | '/$brand/checkout'
    | '/$brand/productos'
    | '/admin/marcas'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/configuracion'
    | '/$brand/'
    | '/admin/'
    | '/$brand/producto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CuentaRoute: typeof CuentaRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SectoresRoute: typeof SectoresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$brand': {
      id: '/$brand'
      path: '/$brand'
      fullPath: '/$brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectores': {
      id: '/sectores'
      path: '/sectores'
      fullPath: '/sectores'
      preLoaderRoute: typeof SectoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$brand/': {
      id: '/$brand/'
      path: '/'
      fullPath: '/$brand/'
      preLoaderRoute: typeof BrandIndexRouteImport
      parentRoute: typeof BrandRoute
    }
    '/$brand/carrito': {
      id: '/$brand/carrito'
      path: '/carrito'
      fullPath: '/$brand/carrito'
      preLoaderRoute: typeof BrandCarritoRouteImport
      parentRoute: typeof BrandRoute
    }
    '/$brand/checkout': {
      id: '/$brand/checkout'
      path: '/checkout'
      fullPath: '/$brand/checkout'
      preLoaderRoute: typeof BrandCheckoutRouteImport
      parentRoute: typeof BrandRoute
    }
    '/$brand/productos': {
      id: '/$brand/productos'
      path: '/productos'
      fullPath: '/$brand/productos'
      preLoaderRoute: typeof BrandProductosRouteImport
      parentRoute: typeof BrandRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marcas': {
      id: '/admin/marcas'
      path: '/marcas'
      fullPath: '/admin/marcas'
      preLoaderRoute: typeof AdminMarcasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$brand/producto/$slug': {
      id: '/$brand/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/$brand/producto/$slug'
      preLoaderRoute: typeof BrandProductoSlugRouteImport
      parentRoute: typeof BrandRoute
    }
  }
}

interface BrandRouteChildren {
  BrandCarritoRoute: typeof BrandCarritoRoute
  BrandCheckoutRoute: typeof BrandCheckoutRoute
  BrandProductosRoute: typeof BrandProductosRoute
  BrandIndexRoute: typeof BrandIndexRoute
  BrandProductoSlugRoute: typeof BrandProductoSlugRoute
}

const BrandRouteChildren: BrandRouteChildren = {
  BrandCarritoRoute: BrandCarritoRoute,
  BrandCheckoutRoute: BrandCheckoutRoute,
  BrandProductosRoute: BrandProductosRoute,
  BrandIndexRoute: BrandIndexRoute,
  BrandProductoSlugRoute: BrandProductoSlugRoute,
}

const BrandRouteWithChildren = BrandRoute._addFileChildren(BrandRouteChildren)

interface AdminRouteChildren {
  AdminMarcasRoute: typeof AdminMarcasRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMarcasRoute: AdminMarcasRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CuentaRoute: CuentaRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SectoresRoute: SectoresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
